//export const ADD_EVENT = 'ADD_EVENT';
export const EVENT_CREATE = 'EVENT_CREATE';
export const TOGGLE_EVENT = 'TOGGLE_EVENT';
export const EVENT_DELETE = 'EVENT_DELETE';
export const EVENT_DELETE_FAIL = 'EVENT_DELETE_FAIL';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const FOLLOW = 'FOLLOW';
export const ENJOY = 'ENJOY';

export const DOWNLOAD_INITIALEVENTLIST = 'DOWNLOAD_INITIALEVENTLIST';
export const DOWNLOAD_INITIALEVENTLIST_START = 'DOWNLOAD_INITIALEVENTLIST_START';
export const DOWNLOAD_INITIALEVENTLIST_SUCCESS = 'DOWNLOAD_INITIALEVENTLIST_SUCCESS';

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const LOGOUT_USER_START = 'LOGOUT_USER_START';
// export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
// export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';

export const CREATE_PROFILE = 'CREATE_PROFILE';

export const TUTORIAL = 'TUTORIAL';

export const INCREMENT = 'INCREMENT';
export const LOAD_PROFILE_START = 'LOAD_PROFILE_START';
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
/*export const LOAD_PROFILE_FAIL = 'LOAD_PROFILE_FAIL';

export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';*/

export const UPDATE_PATH = 'UPDATE_PATH';

export const EVENTLIST_FETCH_SUCCESS = 'EVENTLIST_FETCH_SUCCESS';
export const DOWNLOAD_EVENTLIST = 'DOWNLOAD_EVENTLIST';  //prof

export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE'
};
